name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        jdk: [ 8, 11 ]
    runs-on: ubuntu-latest
    steps:
      - name: Pull Request Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
        if: github.head_ref != ''
      - name: Push Checkout
        uses: actions/checkout@v2
        if: github.head_ref == ''
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{matrix.jdk}}
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f .travis-requirements.txt ]; then pip install -r .travis-requirements.txt; fi
      - name: Github Environment Setup
        run: |
          owner=${{ github.repository_owner }}
          echo "REPO_SITE=${owner}" >> $GITHUB_ENV
      - name: Universe Setup & Build
        run: ./dependency-setup.sh
      - name: Universe Tests
        run: ./test-universe.sh