name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        jdk: [ 8, 11 ]
    runs-on: ubuntu-latest

    steps:
#    - uses: actions/checkout@v2
    - name: Pull Request Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{github.event.pull_request.head.ref}}
        repository: ${{github.event.pull_request.head.repo.full_name}}
      if: github.head_ref != ''
    - name: Push Checkout
      uses: actions/checkout@v2
      if: github.head_ref == ''
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: ${{matrix.jdk}}
        distribution: 'temurin'
    - name: Clone and build dependencies
      run: ./scripts/setup-deps.sh
    - name: Build with Gradle
      uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
      with:
        arguments: test
